version: '2'
services:

    proxy:
        ports:
          - "80:80"
          - 444:444

    cexpressApp:
        volumes:
           - ~/.ssh:/var/www/.ssh
           - ~/.composer:/var/www/.composer