version: '2'
services:
    proxy:
        image: jwilder/nginx-proxy
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro

    database:
        image: mariadb:10.1
        container_name: cexpress-database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: courriers
    app:
        build: docker/app
        image: cexpress/app
        container_name: cexpress-app
        environment:
            VIRTUAL_HOST: cexpress.docker
            DOMAIN_NAME: cexpress.docker
        depends_on:
            - database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: cexpress-phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: database
            VIRTUAL_HOST: phpmyadmin.docker
            DOMAIN_NAME: phpmyadmin.docker
        depends_on:
            - database
