version: '2'
services:
    proxy:
        image: jwilder/nginx-proxy
        container_name: cexpress-proxy
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    database:
        image: mariadb:10.1
        container_name: cexpress-database
        volumes:
            - ./database/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: courriers

    cexpressApp:
        build: docker/php70
        image: cexpress/php70
        container_name: cexpressapp
        volumes:
          - ./web:/var/www/html
        environment:
            VIRTUAL_HOST: cexpress.site.docker
            DOMAIN_NAME: cexpress.site.docker
        depends_on:
            - database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: cexpress-phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: database
            VIRTUAL_HOST: phpmyadmin.docker
            DOMAIN_NAME: phpmyadmin.docker
        depends_on:
          - database
