version: '2'
services:
    proxy:
        image: jwilder/nginx-proxy
        container_name: cexpress-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
          - default

    database:
        image: mariadb
        container_name: cexpress-database
        networks:
            - default
        volumes:
            - database:/var/lib/mariadb:rw
            - /home/icamara/my-projects/cexpress/database:/var/dump
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: courriers
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    app:
        build: docker/app
        image: bagelconer/app
        container_name: cexpress-app
        networks:
            - default
        ports:
            - 8084:80
        volumes:
            - ./web:/var/www/html
            - /home/icamara/.ssh:/root/.ssh
        environment:
            VIRTUAL_HOST: cexpress.docker
        depends_on:
            - database
        links:
            - database:database
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: cexpress-phpmyadmin
        networks:
            - default
        ports:
            - 8082:80
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: database
            VIRTUAL_HOST: phpmyadmin.docker


networks:
    default: {}

volumes:
    database: {}
